version: "3.8"

services:
  app:
    env_file: 
      - .env
    build: './app'
    container_name: 'app'
    restart: 'always'
    expose:
      - '8000'
    volumes:
      - type: 'bind'
        source: './volumes/app'
        target: '/app'
    links:
      - redis
    depends_on:
      - "mariadb"
      - "nginx"
      - "redis"

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - "6379"
  
  mariadb:
    env_file:
      - .env
    image: 'mariadb:latest'
    container_name: 'mariadb'
    restart: 'always'
    expose:
      - '3306'
    volumes:
      - type: 'bind'
        source: './volumes/dbdata'
        target: '/var/lib/mysql'
    links:
      - redis


  nginx:
    build: './nginx'
    container_name: 'nginx'
    restart: 'always'
    ports:
      - '80:80'
    volumes:
      - type: 'bind'
        source: './volumes/media'
        target: '/app/media'

      - type: 'bind'
        source: './volumes/static'
        target: '/app/static'
    links:
      - redis

  celery_worker:
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: 'always'
    command: su -m myuser -c 'sleep 5 && celery -A config worker -l info'
    volumes:
      - ./volumes/app:/app
    links:
      - redis
