# Generated by Django 4.2.8 on 2023-12-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="test_cases",
            field=models.FileField(upload_to="test_cases/"),
        ),
    ]
