# Generated by Django 4.2.8 on 2023-12-26 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0002_alter_problem_test_cases"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="category",
            new_name="categories",
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="language",
            new_name="languages",
        ),
    ]
