# Generated by Django 4.2.8 on 2023-12-27 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0005_problem_contest"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Tag",
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={},
        ),
        migrations.RenameField(
            model_name="problem",
            old_name="categories",
            new_name="tags",
        ),
    ]
