# Generated by Django 4.2.8 on 2023-12-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0007_problem_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="level",
            field=models.CharField(
                choices=[("easy", "ساده"), ("intermediate", "متوسط"), ("hard", "سخت")],
                max_length=12,
            ),
        ),
    ]
