# Generated by Django 4.2.8 on 2023-12-27 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contest",
            old_name="title",
            new_name="name",
        ),
    ]
