# Generated by Django 4.2.8 on 2023-12-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0008_alter_problem_level"),
        ("profiles", "0004_alter_profile_first_name_alter_profile_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("solved", "Solved"),
                            ("partial", "Partial"),
                            ("no-try", "No try"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="problemset.problem",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="problemset",
            field=models.ManyToManyField(
                related_name="profile", to="profiles.userproblem"
            ),
        ),
    ]
