# Generated by Django 4.2.8 on 2023-12-28 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0005_userproblem_profile_problemset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="problemset",
        ),
        migrations.AddField(
            model_name="userproblem",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
