# Generated by Django 4.2.8 on 2023-12-28 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0006_remove_profile_problemset_userproblem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproblem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
