# Generated by Django 4.2.8 on 2023-12-26 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0001_initial"),
        ("problemset", "0004_alter_problem_categories_alter_problem_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="contest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="problems",
                to="contests.contest",
            ),
        ),
    ]
