# Generated by Django 4.2.8 on 2023-12-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0006_rename_category_tag_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="level",
            field=models.CharField(
                choices=[("easy", "ساده"), ("intermediate", "متوسط"), ("hard", "سخت")],
                default="easy",
                max_length=12,
            ),
        ),
    ]
