# Generated by Django 4.2.8 on 2023-12-30 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0010_alter_submission_result_alter_submission_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
