# Generated by Django 4.2.8 on 2023-12-30 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0011_alter_submission_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="submitted_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
