# Generated by Django 4.2.8 on 2023-12-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0012_submission_submitted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="language",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="problemset.language",
            ),
        ),
    ]
