# Generated by Django 4.2.8 on 2023-12-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0013_submission_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="problemset.language"
            ),
        ),
    ]
