# Generated by Django 4.2.8 on 2024-02-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problemset", "0014_alter_submission_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="test_cases",
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_file", models.FileField(upload_to="problem_inputs/")),
                ("output_file", models.FileField(upload_to="problem_outputs/")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problemset.problem",
                    ),
                ),
            ],
        ),
    ]
